---
- hosts: all
  remote_user: root
  tasks:
    - name: to create sam user
      user:
        name: sam
        shell: /bin/bash
    - name: to update installed packages
      lineinfile: 
        line: "DenyUsers sam"
        dest: /etc/ssh/sshd_config
        create: yes
      notify: 
        - restart sshd.service

  handlers:
    - name: restart sshd.service
      service:
        name: sshd
        state: restarted

